### ISSUE TITLE
Turn telemetry off

### ISSUE THREAD

**Issue by jameslan** [beevelop/docker-cordova#25]
When I run `cordova build android`, a prompt saying

```
? May Cordova anonymously report usage statistics to improve the tool over time? 
```

blocks its execution.

I think it will be very helpful if `cordova telemetry off` could be added into dockerfile.

Anyway, Thanks for this convenient image!

**Comment by beevelop** [comment]
@jameslan This does only happen if you are attached to the respective container (e.g. via `run -it`), doesn't it?

I personally don't want to disable this feature by default. I guess the Cordova development teams gets helpful insights about the users' platforms, what helps them in their decision making process (have a look at [this dashboard](https://datastudio.google.com/u/0/org//reporting/0B-Ja5cNOX_XLTElHdWd4V2NUem8/page/xEE)).

Considering your use case: You can manually run `cordova telemetry off` right before you run build commands or provide the `--no-telemetry` flag (e.g. `cordova build --no-telemetry`).
