### ISSUE TITLE
Upgrade to gradle 2.14.1

### ISSUE THREAD

**Issue by jameslan** [beevelop/docker-cordova#26]
The newest cordova-android is using gradle 2.14.1.

However this image is based on beevelop/android which still uses gradle 2.10.

I'm not sure if beevelop/android should upgrade to gradle 2.14 but I do think cordova image should.

**Comment by jarodium** [comment]
I agree.
The full stack should be updated to use the latest versions.
I am currently using this image and every time I wish to build the app for android the box will continue to download https://services.gradle.org/distributions/gradle-4.1-all.zip .
