### ISSUE TITLE
Error with firebase plugins

### ISSUE THREAD

**Issue by Poldan** [beevelop/docker-cordova#34]
When i've added any firebase plugins to my app, i got error:
Could not find com.google.firebase:firebase-core:9.0.0.

p.s. Any another push notices plugins works with this image ?

**Comment by beevelop** [comment]
Could you check if this issue does still exist for `v7.1.0` onwards? Should also be available on the `latest` DockerHub image tag in a few minutes.

**Comment by Poldan** [comment]
https://github.com/arnesson/cordova-plugin-firebase
Compiled!
Working!
You are awesome!
