### ISSUE TITLE
Builds no longer working : major version release of the Google Play Services and Firebase libaries on June 17

### ISSUE THREAD

**Issue by REPTILEHAUS** [beevelop/docker-cordova#48]
always getting aapt2 errors, event when setting it to disabled. more info here 

https://stackoverflow.com/questions/56654226/ionic-cordova-app-stopped-compiling-after-googles-june-17th-firebase-sdk-update/56656680#56656680

**Comment by beevelop** [comment]
Unfortunately there is not much, I can do about it with this image. This is something, the maintainers of either cordova-android of the respective Cordova plugins (firebase, etc.) need to fix.
