### ISSUE TITLE
Old openJDK version in v2023.01.1

### ISSUE THREAD

**Issue by atroy** [beevelop/docker-cordova#67]
I fetched the latest version of cordova and it seems that it does not include the latest java version. 

```
alex@alex-xps:~$ docker run -it beevelop/cordova /bin/bash
root@35b0ef4e70cb:/tmp# java -version
openjdk version "1.8.0_282"
OpenJDK Runtime Environment (build 1.8.0_282-8u282-b08-0ubuntu1~20.04-b08)
OpenJDK 64-Bit Server VM (build 25.282-b08, mixed mode)
```
You could also verify it here:
https://hub.docker.com/layers/beevelop/cordova/v2023.01.1/images/sha256-d4a98aff52e7b8c043a275ee04ec627c6314809963681701223d4617ab52b196?context=explore
search for "java-8"

In the base images it did work unfortunately.

**Comment by sunbiz** [comment]
Cordova 10+ requires [JDK 11](https://cordova.apache.org/docs/en/11.x/guide/platforms/android/index.html#the-required-software-&-tools). So, please upgrade it from JDK 8

**Comment by beevelop** [comment]
The most recent version `v2023.04.1` should resolve the issue and features the following Java version:
```
openjdk version "11.0.17" 2022-10-18
OpenJDK Runtime Environment (build 11.0.17+8-post-Ubuntu-1ubuntu220.04)
OpenJDK 64-Bit Server VM (build 11.0.17+8-post-Ubuntu-1ubuntu220.04, mixed mode, sharing)
```

I hope this resolves the issue. Feedback is highly appreciated 🙏
