### ISSUE TITLE
empty $ANDROID_HOME directory & missing 32.x build-tools in v2023.04.1

### ISSUE THREAD

**Issue by wolfwfr** [beevelop/docker-cordova#71]
Hi Beevelop,

First of all, thank you for your work on preparing these docker images, they have helped us a lot.

However, currently we are facing unexpected issues with the latest version, i.e. `v2023.04.1`.

Despite the recently resolved github-issues, we observed the following:

1. The ANDROID_HOME environment variable is set to `/opt/android/sdk`. However, there does not appear to be any `sdk` directory inside `/opt/android`. Manually changing ANDROID_HOME to `/opt/android` was required for us to resolve the issue where `cordova build android` fails with the message: `Failed to find 'ANDROID_HOME' environment variable. Try setting it manually.`.
2. The `/opt/android/build-tools` directory only contains versions `30.0.3` and `33.0.1`. We are now running into the following error message on `cordova build android`: `No usable Android build tools found. Highest 32.x installed version is 30.0.3; Recommended version is 32.0.0.` Below follows the full error message:

```
FAILURE: Build failed with an exception.

* Where:
Script '/tmp/platforms/android/CordovaLib/cordova.gradle' line: 75

* What went wrong:
A problem occurred evaluating script.
> No usable Android build tools found. Highest 32.x installed version is 30.0.3; Recommended version is 32.0.0.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org
```

Thanks for your help

**Comment by beevelop** [comment]
With the most recent release `v2023.10.1` the issue should be resolved. Thank you for the detailed information. The `ANDROID_HOME` path is fixed upstream in the beevelop/android image. The Android build tools version is now set to `33.0.2` (`34` is already shipped though in the upstream image if necessary).
